### ISSUE TITLE
hide areas without candidates from main page or mark as uploaded

### ISSUE THREAD

**Issue by matkoniecz** [EdwardBetts/osm-wikidata#117]
currently https://osm.wikidata.link/ has "Valley of the Kings" (linking to https://osm.wikidata.link/candidates/way/115773400)

I opened it as it sounded interesting and was welcomed by " 0 candidates found (0 with multiple matches) No candidates."

Maybe either hide such entries or mark them as "Great work, everything is done!" on the main page or something similar?

**Comment by EdwardBetts** [comment]
The main page shows Valley of the Kings with a "tags uploaded" badge. You're right, I should hide areas that are complete.
