### ISSUE TITLE
Button “add wikidata tag to OpenStreetMap” doesn’t work

### ISSUE THREAD

**Issue by hfs** [EdwardBetts/osm-wikidata#119]
On a candidate’s detail page

https://osm.wikidata.link/Q693653

there’s a choice between several matching OSM objects with radio buttons and a button to upload the tag change to OSM directly. The button doesn’t work and has no effect.

My guess is that this is caused by the second radio button and submit button falling out of the `<form>` block.

![osm-wikidata_submit_button](https://user-images.githubusercontent.com/538109/28986658-2f813392-7968-11e7-9a21-853d617b12b8.png)

**Comment by EdwardBetts** [comment]
Thanks for the bug report. You're right, that page is completely broken. The 'report bad match' form is nested in another form. I'm going to rewrite the page to get rid of the nested forms, then it should work.
