### ISSUE TITLE
allow to search by bounding box

### ISSUE THREAD

**Issue by matkoniecz** [EdwardBetts/osm-wikidata#123]
I want to add tags near my location - for multiple reasons, starting from fact that I have a local knowledge.

But

https://osm.wikidata.link/matcher/relation/2768922 is fully processed
https://osm.wikidata.link/matcher/relation/224459 timeouts

I thought about setting up local instance with longer timeouts but that is blocked by #115

**Comment by matkoniecz** [comment]
To clarify: searching by bounding box would allow me to search nearby objects, in area that is not processed, without timeout

**Comment by matkoniecz** [comment]
allowing arbitrary bboxes would also allow for small ones to match also buildings, streets and other things that so far were blocked as it was failing for large areas

**Comment by EdwardBetts** [comment]
For this to work we need to show the user a map and let them select the bounding box.

This leaflet plugin seems appropriate: https://github.com/heyman/leaflet-areaselect/

**Comment by EdwardBetts** [comment]
I've added wikidata query chunking, so https://osm.wikidata.link/candidates/relation/224459 works.
Not sure if we still need search by bounding box.

**Comment by matkoniecz** [comment]
For me it is no longer necessary, thanks!
