### ISSUE TITLE
fails to handle space in user name

### ISSUE THREAD

**Issue by matkoniecz** [EdwardBetts/osm-wikidata#124]
very low importance, but a bug

in https://osm.wikidata.link/changes users with space in username (for example "Mateusz Konieczny") are linked without space in username, as result my link leads to https://www.openstreetmap.org/user/MateuszKonieczny rather than https://www.openstreetmap.org/user/Mateusz%20Konieczny

**Comment by EdwardBetts** [comment]
Python Social Auth is removing spaces from usernames. I've fixed it for future users by adding this to the config:

SOCIAL_AUTH_CLEAN_USERNAMES = False

I've corrected your username in the database, so the links on the recent changes page will work.
