### ISSUE TITLE
allow refreshing data for a location 

### ISSUE THREAD

**Issue by matkoniecz** [EdwardBetts/osm-wikidata#145]
Currently once matches are generated there is no way to invalidate cache

So for example 100% processed https://osm.wikidata.link/no_match/relation/3496261 (I fixed wikidata issues that resulted in a match failure) it will be forever displayed as 75% match at https://osm.wikidata.link/filtered/Poland

**Comment by EdwardBetts** [comment]
I added a refresh button to the candidate page.

**Comment by matkoniecz** [comment]
Thanks!
