### ISSUE TITLE
match natural=bare_rock/rock with Category:Rock_formations

### ISSUE THREAD

**Issue by matkoniecz** [EdwardBetts/osm-wikidata#149]
https://en.wikipedia.org/wiki/Maczuga_Herkulesa is in https://en.wikipedia.org/wiki/Category:Inselbergs in https://en.wikipedia.org/wiki/Category:Rock_formations

Current "Rock formations by country" misses articles that are not categorized by country (for example see https://en.wikipedia.org/wiki/Maczuga_Herkulesa )

**Comment by EdwardBetts** [comment]
The 'by country' but is ignored. The categories for Maczuga Herkulesa were cached and 'Rock formations in Europe' was missing. I've refreshed Ojcowski Park Narodowy so the cache is no longer stale.
See https://osm.wikidata.link/Q6725877
