### ISSUE TITLE
for bridges with multiple matches ignore bridge=* match

### ISSUE THREAD

**Issue by matkoniecz** [EdwardBetts/osm-wikidata#152]
AFAIK https://osm.wikidata.link/Q5529387 is tagged correctly, despite this matcher is unable to recognize https://www.openstreetmap.org/way/175348773#map=18/52.26099/21.01034 as the proper match and ignore others

**Comment by matkoniecz** [comment]
Or maybe just ignore bridge=* match for all bridges? AFAIK man_made=bridge can be always added and bridge wikidata in the end should reside there.

**Comment by EdwardBetts** [comment]
The matching system doesn't work for many bridges. It is looking for a single object in OSM, bridges are often represented as multiple objects. Some large bridges are tagged with man_made=bridge which should work.

Sometimes bridges are added as a single way with bridge=yes, pedestrian bridges for example. These work with the matcher. If bridge=* was ignored then it wouldn't find the match.

**Comment by EdwardBetts** [comment]
Another example: https://osm.wikidata.link/Q26674636

**Comment by EdwardBetts** [comment]
Done.

**Comment by matkoniecz** [comment]
Thanks for fixing, I needed to force rerun of matcher - and then I was able to add bridges in Wrocław :)
