### ISSUE TITLE
use Category:Meadows_by_country for matching

### ISSUE THREAD

**Issue by matkoniecz** [EdwardBetts/osm-wikidata#153]
https://osm.wikidata.link/Q11821511 is an example where it would be useful

May match landuse=meadow, natural=grassland

**Comment by EdwardBetts** [comment]
Currently the code only looks at categories on English Wikipedia. This place doesn't have an article on English Wikipedia.

**Comment by matkoniecz** [comment]
> Currently the code only looks at categories on English Wikipedia.

I was not aware about that.

But before reporting I checked https://github.com/EdwardBetts/osm-wikidata/blob/master/data/entity_types.json it seems that meadow matching is not supported anyway

**Comment by EdwardBetts** [comment]
I've added Meadows and Grasslands. dbec93b
