### ISSUE TITLE
exclude cebwiki

### ISSUE THREAD

**Issue by matkoniecz** [EdwardBetts/osm-wikidata#159]
cebwiki is a parody of wikipedia, populated solely* by "articles" generated by bots. What worse they polluted wikidata with new entries duplicating existing ones.

See https://www.wikidata.org/w/index.php?search=cebwiki+cebuano&title=Special:Search&profile=advanced&fulltext=1&ns4=1&ns120=1&searchToken=1q23bke80mt853jydllunrt82 - for example https://www.wikidata.org/wiki/Wikidata:Project_chat#Cebuano https://www.wikidata.org/wiki/Wikidata:Project_chat/Archive/2017/08#Dealing_with_our_second_planet 

I think that it would be better to ignore wikidata entries that have exactly one interwiki link that points to cebwiki.

*to be more exact - there is some very small number of human-edited articles, mostly reverts of spam

**Comment by EdwardBetts** [comment]
Thanks. I was wondering about cebwiki. I'll do as you suggest.

**Comment by matkoniecz** [comment]
Or at least exclude from "OSM candidate matches multiple Wikidata items"? I encountered this again, almost immediately after going back to using this tool ( https://www.wikidata.org/w/index.php?title=Q1543147&diff=614556052&oldid=614539672 ).

I am interested in improving OSM, not utterly useless cebwiki quagmire on Wikidata.
