### ISSUE TITLE
stop trying to match lists

### ISSUE THREAD

**Issue by matkoniecz** [EdwardBetts/osm-wikidata#160]
https://www.wikidata.org/wiki/Q6435960 is broken in many different ways but

> instance of Wikimedia list article

should be enough to discard it from matching

Found on https://osm.wikidata.link/already_tagged/relation/2768922 tab already tagged

**Comment by EdwardBetts** [comment]
Q6435960 looks like is parliamentary constituency, as opposed to being a list article.

The matcher skips items that link to an article in English that starts with "List of ". This approach won't work for items without an article in English.

I'll make this change.
