### ISSUE TITLE
CC0 in UK, CC0 in USA, sui generis database right and Wikidata

### ISSUE THREAD

**Issue by matkoniecz** [EdwardBetts/osm-wikidata#178]
Hopefully I am wrong, but I am unsure is it OK to use WIkidata data to edit OSM

I hope that I am wrong and you can explain my misunderstanding

I started discussion on talk mailing list: https://lists.openstreetmap.org/pipermail/talk/2017-November/079492.html

**Comment by EdwardBetts** [comment]
This tool links Wikidata and OSM, it doesn't copy data between them. Given that we're just adding a link it doesn't matter that the projects use different licenses.

**Comment by matkoniecz** [comment]
But it is using WIkidata/Wikipedia data to match them. I worry that it may be a problem (hopefully not, but...)
