### ISSUE TITLE
prefer local name over foreign name

### ISSUE THREAD

**Issue by matkoniecz** [EdwardBetts/osm-wikidata#206]
for https://osm.wikidata.link/candidates/relation/2597485

> Gdańsk Power Station (Q5529380)

Polish name is available

> Bartholomäuskirche (Q11742525)

Polish name is available

> 圣彼济达圣殿 (Q11746615) 

Polish name is available

I am not sure what is preferable - local language or language requested by browser, but for place in Poland for user with English-language browser "圣彼济达圣殿" is not a preferred label.

**Comment by EdwardBetts** [comment]
I need a way to figure out the local language. I might be able to do it by figuring out the country, then checking on Wikidata to find the national language for that country. This breaks for regions that use a different language from the national language.

**Comment by matkoniecz** [comment]
For regions - maybe count how many articles are in each Wikipedia version and assume that the most popular is local language version? It would distinguish between popular ones but may break - for example if Polish Wikipedia made bot import of places in random African country it may result in unexpected results.

**Comment by matkoniecz** [comment]
For matches listed on candidate pages - maybe use value of name tag in OSM object?

**Comment by EdwardBetts** [comment]
I think these ideas answer my question of how to figure out which language to use.

**Comment by adivik2000** [comment]
It's best to ask the user for the language input imo just like how osm takes in preferred language. I might be well aware of places in say dubai but don't necessarily know how to read the language. I'd probably have to go through many clicks in the cross check process. 

Also, same as #172
