### ISSUE TITLE
repeated chunks

### ISSUE THREAD

**Issue by matkoniecz** [EdwardBetts/osm-wikidata#207]
https://osm.wikidata.link/matcher/relation/130957 for me had following log

including for example

> chunk 11 downloaded
> chunk 11 downloaded

Full log up to this moment:

> Split into 49 chunks, of which 11 are empty.
> current: extracts loaded
> retrieving items from wikidata
> downloading wikidata in 25 chunks
> requesting wikidata chunk 1
> requesting wikidata chunk 2
> requesting wikidata chunk 3
> requesting wikidata chunk 4
> requesting wikidata chunk 5
> requesting wikidata chunk 6
> requesting wikidata chunk 7
> requesting wikidata chunk 8
> requesting wikidata chunk 9
> requesting wikidata chunk 10
> requesting wikidata chunk 11
> requesting wikidata chunk 12
> requesting wikidata chunk 13
> requesting wikidata chunk 14
> requesting wikidata chunk 15
> requesting wikidata chunk 16
> requesting wikidata chunk 17
> requesting wikidata chunk 18
> requesting wikidata chunk 19
> requesting wikidata chunk 20
> requesting wikidata chunk 21
> requesting wikidata chunk 22
> requesting wikidata chunk 23
> requesting wikidata chunk 24
> requesting wikidata chunk 25
> wikidata query complete
> loading categories from English language Wikipedia
> categories loaded
> items saved to database
> 5,084 Wikidata items found
> getting wikidata item details
> loading wikipedia extracts
> downloading data from overpass
> connected to task queue
> requesting chunk 3
> chunk 3 downloaded
> requesting chunk 4
> chunk 4 downloaded
> requesting chunk 5
> chunk 5 downloaded
> requesting chunk 6
> chunk 6 downloaded
> requesting chunk 8
> chunk 8 downloaded
> requesting chunk 9
> chunk 9 downloaded
> requesting chunk 10
> chunk 10 downloaded
> chunk 11 downloaded
> chunk 11 downloaded
> requesting chunk 12
> chunk 12 downloaded
> requesting chunk 15
> chunk 15 downloaded
> requesting chunk 16
> chunk 16 downloaded
> requesting chunk 17
> chunk 17 downloaded
> requesting chunk 18
> chunk 18 downloaded
> requesting chunk 19
> chunk 19 downloaded
> requesting chunk 20
> chunk 20 downloaded
> chunk 22 downloaded
> chunk 22 downloaded
> requesting chunk 23
> chunk 23 downloaded
> requesting chunk 24
> chunk 24 downloaded
> requesting chunk 25
> chunk 25 downloaded
> requesting chunk 26

**Comment by EdwardBetts** [comment]
The overpass download broadcasts to all connected matcher processes. You're seeing the feedback from two simultaneous overpass downloads.
