### ISSUE TITLE
list administrative  subareas of too large areas

### ISSUE THREAD

**Issue by matkoniecz** [EdwardBetts/osm-wikidata#220]
https://osm.wikidata.link/search?q=Nigeria - Nigeria is too large so displaying results of 

<pre>
[out:json][timeout:3600];
area
  ['name:pl'=Nigeria] -> .parent_area;
(
  rel
    (area.parent_area)
    [admin_level=4][boundary=administrative];
);
out;
</pre>

with links would be helpful

**Comment by EdwardBetts** [comment]
There is now a browse interface, generated from information in Wikidata. Here are some examples:

Nigeria: https://osm.wikidata.link/browse/Q1033
USA: https://osm.wikidata.link/browse/Q30
Poland: https://osm.wikidata.link/browse/Q36

I'm going to change the search results page to include browse links and adjust the big area warning page to show the browse interface.
