### ISSUE TITLE
Show not only Wikidata marker on leaflet map

### ISSUE THREAD

**Issue by sascha-hendel** [EdwardBetts/osm-wikidata#251]
Right now on the leaflet mapbox You can see a marker with Wikidata lat/long position on OSM map, but the related item(s) from OSM (nodes, ways) are not marked in any way. It would be very helpful if the OSM   matches could be highlighted (with mouseover effect fo multiple matches).

**Comment by EdwardBetts** [comment]
I'm working on this.

**Comment by EdwardBetts** [comment]
The 'show on map' link will highlight the associated OSM objects.

**Comment by sascha-hendel** [comment]
Can You highlight the associated OSM object(s) in the detail pages, too? 
[Example page:](https://osm.wikidata.link/detail/Q1773894/way/59359987)
