### ISSUE TITLE
Added tags are sometimes yellow?

### ISSUE THREAD

**Issue by sascha-hendel** [EdwardBetts/osm-wikidata#252]
After submitting a changeset, most items get a green background, but sometimes items get a yellow one.
What does this mean? Is the update not successful?
Can You add a legend/explanation therefore on the submit pages?

**Comment by EdwardBetts** [comment]
Yes, yellow is an error saving the edit. I'll add some text to explain and make the add tags page show the reason the tag can't be added.

**Comment by EdwardBetts** [comment]
Either the OSM object was deleted, or it had already had a wikidata tag.

The candidate page shouldn't be showing these matches to the user. I'm thinking of changing it so if the data on the candidate page is a few days old it'll check each OSM object to see if it has been deleted or a tag added in the meantime. I'll do this via a websocket, so it doesn't slow initial render of the candidate page.

**Comment by EdwardBetts** [comment]
I think I've found and fix this problem. Some matches were being skipped because the OSM object had a tag that contained wikidata, like **brand:wikidata** or **subject:wikidata**. The code will now only skip items that genuinely already have a **wikidata** tag.
