### ISSUE TITLE
KeyError: 'isa_list' for Antarctica

### ISSUE THREAD

**Issue by picsi** [EdwardBetts/osm-wikidata#392]
URL: https://osm.wikidata.link/browse/Q51

>Traceback (most recent call last):
>  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
>    response = self.full_dispatch_request()
>  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
>    rv = self.handle_user_exception(e)
>  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
>    reraise(exc_type, exc_value, tb)
>  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
>    raise value
>  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
>    rv = self.dispatch_request()
>  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
>    return self.view_functions[rule.endpoint](**req.view_args)
>  File "/srv/osm-wikidata/matcher/view.py", line 1053, in browse_page
>    rows = wikidata.next_level_places(qid, entity)
>  File "/srv/osm-wikidata/matcher/wikidata.py", line 812, in next_level_places
>    for url in row['isa_list']['value'].split(' '):
>KeyError: 'isa_list'

**Comment by EdwardBetts** [comment]
I'm pretty sure this error is being triggered by a Wikidata query timeout.

**Comment by picsi** [comment]
Just tried again and hit the same issue.

**Comment by picsi** [comment]
Similar problem for https://osm.wikidata.link/browse/Q184319

**Comment by EdwardBetts** [comment]
Here is the query for Antarctica (Q51). There are 19,123 results: http://tinyurl.com/ybu5trba
```
SELECT` DISTINCT ?item
                ?itemLabel
                ?startLabel
                (SAMPLE(?pop) AS ?pop)
                (SAMPLE(?area) AS ?area)
WHERE {
  VALUES ?start { wd:Q51 } .
  VALUES (?country) {
    (wd:Q3624078)  # sovereign state
    (wd:Q161243)   # dependent territory
    (wd:Q179164)   # unitary state
    (wd:Q1763527)  # constituent country
  }

  ?item wdt:P30 ?start .
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q15893266 } .
  FILTER NOT EXISTS { ?item wdt:P576 ?end } .
  OPTIONAL { ?item wdt:P1082 ?pop } .
  OPTIONAL { ?item wdt:P2046 ?area } .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
}
GROUP BY ?item ?itemLabel ?startLabel
ORDER BY ?itemLabel
```

**Comment by EdwardBetts** [comment]
This is fixed.
