### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by adivik2000** [EdwardBetts/osm-wikidata#425]
Unable to login. Throws a HTTP Error 401 with -> Client Error: Unauthorized for url: https://www.openstreetmap.org/api/0.6/user/details

**Comment by EdwardBetts** [comment]
I can reproduce this. I'll debug it.

**Comment by EdwardBetts** [comment]
Thanks for the report, this is fixed now.

**Comment by adivik2000** [comment]
That was quick. Thank you! 👍
