### ISSUE TITLE
log in not working properly

### ISSUE THREAD

**Issue by camelCaseNick** [EdwardBetts/osm-wikidata#529]
The OpenStreetMap OAuth link works, but afterwards the _login with OSM_ link still appears instead of the account, settings and log out links. Furthermore the individual item pages have the _login to upload wikidata tags_ and the _add_tags_ pages do not display an error or login button, but do not upload. (I only got to the latter from a cached page – on a not cached candidate list page the login buttons appear instead–, maybe that's why I got there.)
I'm not sure whether it might help, but the _About_ drop-down does not work and instead of course gets me to example.com.

**Comment by EdwardBetts** [comment]
Thanks for the bug report. Try again, it should work for you.
