### ISSUE TITLE
error opening changeset

### ISSUE THREAD

**Issue by wlovotti** [EdwardBetts/osm-wikidata#538]
I am not able to save a changeset due to this error: "error opening changeset". I have tried multiple locations and I get the same error. I am logged in to my OSM account and I am able to successfully edit on OSM directly, so not sure what could be causing this. 

Below are the two locations I attempted to submit changesets for, if that helps traceback the error:

https://osm.wikidata.link/candidates/relation/1933746
https://osm.wikidata.link/candidates/relation/11052530

**Comment by EdwardBetts** [comment]
This is fixed. Let me know if you still have problems.
