### ISSUE TITLE
Indian reserve "boundary=aboriginal_lands"

### ISSUE THREAD

**Issue by hroest** [EdwardBetts/osm-wikidata#562]
This link https://osm.wikidata.link/Q22434215 should match:

* https://www.openstreetmap.org/relation/9451122 boundary=aboriginal_lands
* https://www.wikidata.org/wiki/Q22434215 instance of https://www.wikidata.org/wiki/Q155239

however due to the matching rules, it looks for "boundary=administrative, admin_level" only. Can you add "boundary=aboriginal_lands" to the matcher?

See also

* https://wiki.openstreetmap.org/wiki/Key:boundary
* https://wiki.openstreetmap.org/wiki/Tag:boundary=aboriginal lands

**Comment by EdwardBetts** [comment]
Done
