### ISSUE TITLE
False negative "No matches"

### ISSUE THREAD

**Issue by Dimitar5555** [EdwardBetts/osm-wikidata#625]
I've checked a few of the no matches in https://osm.wikidata.link/no_match/relation/1739530 and they should've matched. The villages have both `name` and `name:en` which in most cases matches with what wikidata has (in cases where it doesn't match, there is a slight variation in the transliteration).

**Comment by EdwardBetts** [comment]
Thanks. I reran the matcher and it found 223 matches.

https://osm.wikidata.link/candidates/relation/1739530
