### ISSUE TITLE
Error when trying to run the Matcher

### ISSUE THREAD

**Issue by thibaultmol** [EdwardBetts/osm-wikidata#630]
I tried multiple towns near me and they all result in an error
https://osm.wikidata.link/matcher/relation/2243488
https://osm.wikidata.link/matcher/relation/2245989
https://osm.wikidata.link/matcher/relation/2245989

https://www.whatsmybrowser.org/b/O6XR2

**Comment by EdwardBetts** [comment]
Thanks, this was a problem with the Overpass API. I switched to a different Overpass API endpoint and it is working now.
