### ISSUE TITLE
TimeoutError when trying to run the matcher anywhere

### ISSUE THREAD

**Issue by nicolasmaia** [EdwardBetts/osm-wikidata#642]
@EdwardBetts Error message: TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)

When trying to run the matcher here: https://osm.wikidata.link/matcher/relation/11156533

**Comment by EdwardBetts** [comment]
I've restarted the matcher queue and it is working again. I still need to add better monitoring.
