### ISSUE TITLE
Match candidates tab loading never ends

### ISSUE THREAD

**Issue by adrienandrem** [EdwardBetts/osm-wikidata#646]
Processing seems to go well and the message "The matcher has finished." is displayed, but nothing appears in the Match candidates tab except "Loading …".
I get this for https://osm.wikidata.link/candidates/relation/1663791

**Comment by geraki** [comment]
Happens to me also, maybe at 50% of my queries end with "Loading …"
https://osm.wikidata.link/candidates/relation/2238560
https://osm.wikidata.link/candidates/relation/2246176
even queries that run smoothly some years ago, newer queries of same area fail: https://osm.wikidata.link/candidates/relation/563226

**Comment by adrienandrem** [comment]
It seems fixed.

@geraki does it work now for you?

**Comment by geraki** [comment]
@adrienandrem yes it is fixed. Thank you!

**Comment by adrienandrem** [comment]
All credits to EdwardBetts, I'm only reporting bugs :)  
Closing...
