### ISSUE TITLE
502 Bad Gateway for map.osm

### ISSUE THREAD

**Issue by ivanbranco** [EdwardBetts/osm-wikidata#648]
Hi,

I noticed that https://map.osm.wikidata.link/ gives the following error:
"502 Bad Gateway
nginx/1.20.2"

**Comment by EdwardBetts** [comment]
Sorry, I don't have good monitoring yet. It is at the top of my todo list.

There was a configuration error, something to do with IPv6 had broken on the server. I changed a config setting from "localhost" to "127.0.0.1" and it is working now.
