### ISSUE TITLE
Internal Server Error when searching Kojetín

### ISSUE THREAD

**Issue by kudlav** [EdwardBetts/osm-wikidata#654]
https://osm.wikidata.link/search?q=Kojet%C3%ADn
or
https://osm.wikidata.link/search?q=Jasenice

1. Visit https://osm.wikidata.link/
2. Enter Kojetín
3. The app crashes

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by danieldegroot2** [comment]
Workaround: Search "město Kojetin"/"Kojetin město" or "town Kojetin"/"Kojetin town".

**Comment by EdwardBetts** [comment]
I've fixed this bug. Sorry it took so long.
