### ISSUE TITLE
Internal Server Error when searching Wageningen

### ISSUE THREAD

**Issue by danieldegroot2** [EdwardBetts/osm-wikidata#657]
( follow-up to https://github.com/EdwardBetts/osm-wikidata/issues/654 )

https://osm.wikidata.link/search?q=Wageningen

Visit https://osm.wikidata.link/
Enter Wageningen
The app crashes
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by EdwardBetts** [comment]
Thanks. I've fixed this one. I've updated production. I'll push the code soon.
