### ISSUE TITLE
test case: no matches  "Zero Kilometre Stone"

### ISSUE THREAD

**Issue by ImreSamu** [EdwardBetts/osm-wikidata#66]
I have found an interesting case in the no matches group.

Test area:  https://osm.wikidata.link/no_match/relation/221984
"Items with no match found in OSM"
* https://www.wikidata.org/wiki/Q161181 

 But there is a match: https://www.openstreetmap.org/node/736070388

details:
[Zero Kilometre Stone (Q161181)](https://osm.wikidata.link/Q161181)
*  "Wikipedia categories: Buildings and structures in Budapest, Geodetic datums, Individual signs, Street furniture, Transport in Hungary"

The algorithm is not found  this OSM POI with `wikidata=Q161181` ( https://www.openstreetmap.org/node/736070388 )
```xml
<tag k="artwork_type" v="sculpture"/>
<tag k="historic" v="memorial"/>
<tag k="name" v="„0” kilométerkő"/>
<tag k="name:de" v="0-km-Stein"/>
<tag k="name:en" v="Zero Kilometre Stone"/>
<tag k="name:lt" v="Nulio kilometro akmuo"/>
<tag k="name:ru" v="Нулевой километр"/>
<tag k="tourism" v="artwork"/>
<tag k="wikidata" v="Q161181"/>
<tag k="wikipedia" v="hu:„0” kilométerkő"/>
```

**Comment by EdwardBetts** [comment]
The matcher is looking for POIs based on the English Wikipedia article categories: Buildings and structures in Budapest, Street furniture, Transport in Hungary, Geodetic datums, and Individual signs.

The individual match page also considers OSM tags based on the Wikidata 'instance of' property. I've added the article to two sculpture category and added 'instance of' sculpture on Wikidata.

This page is now showing the match: https://osm.wikidata.link/Q161181

I have a plan to fall back to simple name matching if the search based on tags doesn't find anything.

**Comment by ImreSamu** [comment]
thank you,

*  my use case is just adding a missing `wikidata` tag to the OSM in my area.  And at this stage, I don't want to add other Wikidata tags ( like  'instance of' property  ) for matching.
So my expectation was -  I will improve the "no matching" group with adding some OSM `wikidata` tags, but this ["Zero Kilometre Stone" OSM POI](https://www.openstreetmap.org/node/736070388)  already contained the `wikidata` tags

Maybe I will wait for the "wikidata" matching functionality  ( https://github.com/EdwardBetts/osm-wikidata/issues/33 ) 

Thank you for this tool!
