### ISSUE TITLE
lxml.etree.XMLSyntaxError while adding Wikidata for New Delhi

### ISSUE THREAD

**Issue by planemad** [EdwardBetts/osm-wikidata#67]
Getting a python error when adding Wikidata tags for [New Delhi](https://osm.wikidata.link/candidates/relation/2763541), you can add for the default selection, all of which is correct.

This is this is the error https://pastebin.ca/3822032

**Comment by EdwardBetts** [comment]
The error is because node 2148678738 has been deleted. I'll adjust the code to skip deleted nodes.

**Comment by EdwardBetts** [comment]
I think I've fixed it. Try now.

**Comment by planemad** [comment]
❤️
