### ISSUE TITLE
Cannot commit

### ISSUE THREAD

**Issue by james2432** [EdwardBetts/osm-wikidata#91]
I tried commiting 9 items:
Hintonburg (Q4497833)

	name=Hintonburg 	(node, 704 m) 	place
Centretown United Church (Q5062705)

	name=Centretown United Church 	(way, 9 m) 	amenity=place_of_worship, religion=christian, building=church, building
Confederation Station (Q5159795)

	Confederation 	(node, 2 m) 	railway=station
D. Roy Kennedy Public School (Q5203800)

	name=D.Roy Kennedy Public School 	(way) 	amenity=school
Dalmeny, Ontario (Q5211553)

	name=Dalmeny 	(node, 64 m) 	place
Glebe Community Centre (Q5567428)

	name=Glebe Community Centre 	(way) 	amenity=community_centre
Mooney's Bay Park (Q6907736)

	name=Mooney's Bay Park 	(way) 	leisure=park
Ottawa School of Art (Q7109239)

	name=Ottawa School of Art 	(way, 20 m) 	building=school
Westminster Presbyterian Church (Q7989190)

	name=Westminster Presbyterian Church 	(way) 	amenity=place_of_worship, religion=christian, building=church, building 

And it just sticks on opening changeset

**Comment by EdwardBetts** [comment]
Server is overloaded. I'm trying to fix it.

**Comment by EdwardBetts** [comment]
Try now. I'll continue to monitor.

**Comment by james2432** [comment]
Seems to be better, but just reaaaaaaaaaaaaaaally slow.

**Comment by EdwardBetts** [comment]
I've fixed the slowness. IPv6 was broken on the server, every attempt to access the OSM API triggered a 9 second IPv6 timeout. I've disabled IPv6 and it is much faster.
