### ISSUE TITLE
Some places already have wikidata

### ISSUE THREAD

**Issue by james2432** [EdwardBetts/osm-wikidata#92]
Some places already have wikidata tags for example:
Hog's Back Falls (Q4498665)
    node: Prince of Wales Falls (OSM) 46 m from Wikidata best match [show tags] [report bad match]

https://www.openstreetmap.org/node/440938851

Edited 26 days ago(added the wikipedia & wikidata tags) yet in the application still says it could be edited/matched

**Comment by EdwardBetts** [comment]
You're right. The data is cached and gets stale. I've written some code to update the wikidata tags for all cached places. It has fixed this problem for now, but I still need to automate it to run every so often.

There was a button on the candidate page to refresh all the candidate tags, but it was hard to explain exactly what it did, so I removed it. I'll look at bringing it back but with a better explanation.

**Comment by alemela** [comment]
my2c: maybe a solution can be automatically refresh data when a user visit a list. Like if everyone is pushing the button. In this way you don't need to have all the data fresh but just the ones used.

**Comment by EdwardBetts** [comment]
There is now a refresh button on the list of candidate matches.
I've refreshed Ottawa. https://osm.wikidata.link/candidates/relation/4136816

**Comment by matkoniecz** [comment]
I think that the refresh button fixes the problem (as performance is not allowing to constantly refresh all data)
